/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dod.menu;

/**
 *
 * @author Victus
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuTitle = new javax.swing.JLabel();
        mainMenuTitle1 = new javax.swing.JLabel();
        mainMenuTitle2 = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        tutorialLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        playLabel2 = new javax.swing.JLabel();
        play = new javax.swing.JButton();
        tutorial = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 565));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainMenuTitle.setFont(new java.awt.Font("Viner Hand ITC", 3, 64)); // NOI18N
        mainMenuTitle.setForeground(new java.awt.Color(255, 0, 0));
        mainMenuTitle.setText("Die ");
        getContentPane().add(mainMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, 90));

        mainMenuTitle1.setFont(new java.awt.Font("Viner Hand ITC", 3, 64)); // NOI18N
        mainMenuTitle1.setText("Dice");
        getContentPane().add(mainMenuTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, 90));

        mainMenuTitle2.setFont(new java.awt.Font("Viner Hand ITC", 3, 64)); // NOI18N
        mainMenuTitle2.setForeground(new java.awt.Color(153, 153, 153));
        mainMenuTitle2.setText("or");
        getContentPane().add(mainMenuTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 90));

        subtitle.setFont(new java.awt.Font("Viner Hand ITC", 2, 18)); // NOI18N
        subtitle.setText("Press \"Start Game\" to enter the Dungeon.. If you dare..");
        getContentPane().add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 30));

        tutorialLabel.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        tutorialLabel.setForeground(new java.awt.Color(0, 0, 0));
        tutorialLabel.setText("How to Play");
        getContentPane().add(tutorialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 120, -1));

        exitLabel.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(0, 0, 0));
        exitLabel.setText("Exit   Game");
        getContentPane().add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        playLabel2.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        playLabel2.setForeground(new java.awt.Color(0, 0, 0));
        playLabel2.setText("Start Game");
        getContentPane().add(playLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 110, -1));

        play.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dod/menu/assets/btn-150px.png"))); // NOI18N
        play.setBorderPainted(false);
        play.setContentAreaFilled(false);
        play.addActionListener(this::playActionPerformed);
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, 100));

        tutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dod/menu/assets/btn-150px.png"))); // NOI18N
        tutorial.setBorderPainted(false);
        tutorial.setContentAreaFilled(false);
        tutorial.addActionListener(this::tutorialActionPerformed);
        getContentPane().add(tutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dod/menu/assets/btn-150px.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dod/menu/assets/menu.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playActionPerformed

    private void tutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel mainMenuTitle;
    private javax.swing.JLabel mainMenuTitle1;
    private javax.swing.JLabel mainMenuTitle2;
    private javax.swing.JButton play;
    private javax.swing.JLabel playLabel2;
    private javax.swing.JLabel subtitle;
    private javax.swing.JButton tutorial;
    private javax.swing.JLabel tutorialLabel;
    // End of variables declaration//GEN-END:variables
}
