/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dod.menu;

/**
 *
 * @author Victus
 */
public class tutorial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tutorial.class.getName());

    /**
     * Creates new form tutorial
     */
    public tutorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        page1 = new javax.swing.JLabel();
        page2 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        Retrun = new javax.swing.JButton();
        tutorialBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        title.setText("How to Play :");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        page1.setFont(new java.awt.Font("Viner Hand ITC", 0, 13)); // NOI18N
        page1.setForeground(new java.awt.Color(0, 0, 0));
        page1.setText("<html> 1. Players decide who goes first by each rolling the dice — highest roll goes first. <br> <br> 2. Players alternate turns, no skipping. <br> <br> 3. Roll a standard 6-sided dice each turn. <br> <br> 4. Move forward by the number rolled. <br> <br> 5. The tile landed on triggers its effect immediately.</html>");
        page1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 300));

        page2.setFont(new java.awt.Font("Viner Hand ITC", 0, 12)); // NOI18N
        page2.setForeground(new java.awt.Color(0, 0, 0));
        page2.setText("<html> 6. Landing on a Forward, Backward, or Gamble tile may chain into another tile effect. <br> <br> 7. Shield blocks the next Lava tile only — consumed after one use, cannot be stacked. <br> <br> 8. Players cannot go below tile 1 regardless of backward movement. <br> <br> 9. Tile 1 and tile 64 are always Safe tiles. <br> <br> 10. The board layout is randomized at the start of every game. </html>");
        page2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 240, 310));

        menu.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 0, 0));
        menu.setText("Main Menu");
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 30));

        Retrun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dod/menu/assets/btn-100px.png"))); // NOI18N
        Retrun.setBorderPainted(false);
        Retrun.setContentAreaFilled(false);
        getContentPane().add(Retrun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        tutorialBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dod/menu/assets/tutorialBG (3).png"))); // NOI18N
        getContentPane().add(tutorialBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -90, 1320, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tutorial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retrun;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel page1;
    private javax.swing.JLabel page2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tutorialBG;
    // End of variables declaration//GEN-END:variables
}
